import { trackSelfDescribingEvent, CommonEventProperties, SelfDescribingJson } from '@snowplow/browser-tracker';
// Automatically generated by Snowtype

/**
 * Structure for events that identify a user, with their user pieces
 */
export type CustomerIdentification = {
    /**
     * Customer's email address
     */
    email?: null | string;
    /**
     * The customer's phone
     */
    phone?: null | string;
}

/**
 * Data structure related to video details.
 */
export type VideoDetails = {
    /**
     * The video title
     */
    title: string;
}

/**
 * Details about the video category
 */
export type VideoCategory = {
    /**
     * The video category name.
     */
    name: string;
}


type ContextsOrTimestamp<T = any> = Omit<CommonEventProperties<T>, 'context'> & { context?: SelfDescribingJson<T>[] | null | undefined }
/**
 * Track a Snowplow event for CustomerIdentification.
 * Structure for events that identify a user, with their user pieces
 */
export function trackCustomerIdentification<T extends {} = any>(customerIdentification: CustomerIdentification & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = customerIdentification;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosenterprises/customer_identification/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow CustomerIdentification entity.
 */
export function createCustomerIdentification(customerIdentification: CustomerIdentification){
    return {
        schema: 'iglu:com.leosenterprises/customer_identification/jsonschema/1-0-0',
        data: customerIdentification
    }
}
/**
 * Track a Snowplow event for VideoDetails.
 * Data structure related to video details.
 */
export function trackVideoDetails<T extends {} = any>(videoDetails: VideoDetails & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = videoDetails;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosretrogamingflix/video_details/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow VideoDetails entity.
 */
export function createVideoDetails(videoDetails: VideoDetails){
    return {
        schema: 'iglu:com.leosretrogamingflix/video_details/jsonschema/1-0-0',
        data: videoDetails
    }
}
/**
 * Track a Snowplow event for VideoCategory.
 * Details about the video category
 */
export function trackVideoCategory<T extends {} = any>(videoCategory: VideoCategory & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = videoCategory;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.leosretrogamingflix/video_category/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow VideoCategory entity.
 */
export function createVideoCategory(videoCategory: VideoCategory){
    return {
        schema: 'iglu:com.leosretrogamingflix/video_category/jsonschema/1-0-0',
        data: videoCategory
    }
}



